"""
youtube_auth.py — Shared YouTube OAuth2 credentials helper.

Priority order for obtaining credentials:
  1. Env vars: YOUTUBE_CLIENT_ID + YOUTUBE_CLIENT_SECRET + YOUTUBE_REFRESH_TOKEN
     (used in GitHub Actions CI — set these as repository secrets)
  2. pipeline/cache/youtube_token.json on disk
     (generated by setup_youtube_auth.py on first local run)
"""
import json
import os
from pathlib import Path

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
TOKEN_FILE = Path(__file__).parent / "cache" / "youtube_token.json"


def get_credentials():
    """Return valid Google OAuth2 Credentials, auto-refreshing if expired."""
    try:
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
    except ImportError:
        raise ImportError(
            "google-auth not installed. Run: pip install -r requirements-youtube.txt"
        )

    client_id = os.environ.get("YOUTUBE_CLIENT_ID")
    client_secret = os.environ.get("YOUTUBE_CLIENT_SECRET")
    refresh_token = os.environ.get("YOUTUBE_REFRESH_TOKEN")

    if refresh_token and client_id and client_secret:
        # CI path: build credentials directly from env vars
        creds = Credentials(
            token=None,
            refresh_token=refresh_token,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=client_id,
            client_secret=client_secret,
            scopes=SCOPES,
        )
        creds.refresh(Request())
        return creds

    # Local path: load from token file
    if not TOKEN_FILE.exists():
        raise FileNotFoundError(
            "YouTube credentials not found.\n"
            "Run setup_youtube_auth.py first to generate pipeline/cache/youtube_token.json,\n"
            "or set YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, YOUTUBE_REFRESH_TOKEN env vars."
        )

    if not client_id or not client_secret:
        raise EnvironmentError(
            "YOUTUBE_CLIENT_ID and YOUTUBE_CLIENT_SECRET must be set even for local token refresh."
        )

    creds_data = json.loads(TOKEN_FILE.read_text())
    creds = Credentials(
        token=creds_data.get("token"),
        refresh_token=creds_data["refresh_token"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=client_id,
        client_secret=client_secret,
        scopes=SCOPES,
    )

    if creds.expired or not creds.valid:
        creds.refresh(Request())
        # Persist the refreshed token
        TOKEN_FILE.write_text(
            json.dumps(
                {
                    "token": creds.token,
                    "refresh_token": creds.refresh_token,
                    "token_uri": creds.token_uri,
                    "client_id": creds.client_id,
                    "client_secret": creds.client_secret,
                    "scopes": list(creds.scopes or []),
                }
            )
        )

    return creds
